name: bmi
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0" # Updated SDK constraint to support null safety

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0  # Updated to a newer version for compatibility
  font_awesome_flutter: ^10.0.0  # Updated to a newer version for compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
