name: bmi
description: "bmi calculator"


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.0"

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icon.png"

flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

